version: '3.2'

services:

#================================================================================================
# PGADMIN
#================================================================================================
  pgadmin:
    restart: always
    build:
      context: .
    ports:
      - "8114:80"
    depends_on:
      - postgresql
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./session/pgadmin:/sessions                                  # volume for sessions
    environment:
      - PGADMIN_VERSION=3.0
      - PGADMIN_DEFAULT_EMAIL=laradock@laradock.io
      - PGADMIN_DEFAULT_PASSWORD=password
 